### ISSUE TITLE
Reading Wk 2

### ISSUE THREAD

**Issue by sunaynagoel** [DS4PS/cpp-526-fall-2019#13]
This is in required reading for Week 2.

Group of Interest:

female
age over 30
graduate degree
Translated to R as a logical statement:

gender == "female" & age > 30 & grad.degree == FALSE

I was wondering if this statement should be 
gender == "female" & age > 30 & grad.degree == TRUE  instead of the above given. 

Any insights?

**Comment by lecy** [comment]
That's right. That is a typo. Thanks for catching - it has been updated.
