### ISSUE TITLE
Lab 4: R does not seem to be recognizing the shiny functions

### ISSUE THREAD

**Issue by RickyDuran** [DS4PS/cpp-526-fall-2019#19]
When trying to enter code into selectInput () and renderPlot ({}), I get the following errors:
````{r}
selectInput( inputId= "team.widget",
             label= "Select A Team",
             choices= c( "Cincinnati Reds" , "Pittsburgh Pirates" , "Philadelphia Phillies" ,  "St. Louis Cardinals" , "Chicago White Sox" , "Detroit Tigers" , "Chicago Cubs" , "Boston Red Sox" , "New York Yankees" , "Cleveland Indians" ),
             selected= "Cincinnati Reds"   
           )
````
_Error in selectInput(inputId = "team.widget", label = "Select A Team",  : 
  could not find function "selectInput"_

_Error in renderPlot({ : could not find function "renderPlot"_

**Comment by lecy** [comment]
Have you installed Shiny? 

I can't remember off the top of my head if you need to load Shiny in order to run chunks, or if it does it automatically when you include the shiny runtime command in the header.

**Comment by lecy** [comment]
Specifically, are you getting these errors when running chunks, or when knitting?

**Comment by RickyDuran** [comment]
I tried it without installing shiny and got the error, so added the code install.packages( "shiny" ) &
install.packages( "flexdashboard" ) and still got the errors.

**Comment by RickyDuran** [comment]
Although, I also get this message when installing the packages
`Installing package into �C:/Users/rduran3/Documents/R/win-library/3.6�
(as �lib� is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/shiny_1.3.2.zip'
Content type 'application/zip' length 4694929 bytes (4.5 MB)
downloaded 4.5 MB

package ‘shiny’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\rduran3\AppData\Local\Temp\Rtmpe8MbkQ\downloaded_packages
Installing package into �C:/Users/rduran3/Documents/R/win-library/3.6�
(as �lib� is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/flexdashboard_0.5.1.1.zip'
Content type 'application/zip' length 188026 bytes (183 KB)
downloaded 183 KB

package ‘flexdashboard’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\rduran3\AppData\Local\Temp\Rtmpe8MbkQ\downloaded_packages`

**Comment by lecy** [comment]
Are you getting these errors when running chunks, or when knitting? I'm assuming chunks.

**Comment by RickyDuran** [comment]
After running the chunks.

**Comment by lecy** [comment]
Try knitting the file, and I believe it will work then. 

It can't access the functions if not loaded. So although you don't need to include the typical load function for shiny in your RMD in order to knit:

```r
library( shiny )
```

You would need to load shiny if you want to run chunks directly. You can type it in the console, or add a load statement in the code (it won't hurt anything if you load the package explicitly while knitting).

**Comment by RickyDuran** [comment]
After rebooting R, I was able to get it going. Although now I am receiving the following message when trying to run my main chunk of code:

function (...) 
{
    if (length(outputArgs) != 0 && !hasExecuted$get()) {
        warning("Unused argument: outputArgs. The argument outputArgs is only ", 
            "meant to be used when embedding snippets of Shiny code in an ", 
            "R Markdown code chunk (using runtime: shiny). When running a ", 
            "full Shiny app, please set the output arguments directly in ", 
            "the corresponding output function of your UI code.")
        hasExecuted$set(TRUE)
    }
    if (is.null(formals(origRenderFunc))) 
        origRenderFunc()
    else origRenderFunc(...)
}
<bytecode: 0x00000296ece2c288>
<environment: 0x00000296f29f2a28>
attr(,"class")
[1] "shiny.render.function" "function"             
attr(,"outputFunc")
function (outputId, width = "100%", height = "400px", 
    click = NULL, dblclick = NULL, hover = NULL, hoverDelay = NULL, 
    hoverDelayType = NULL, brush = NULL, clickId = NULL, hoverId = NULL, 
    inline = FALSE) 
{
    res <- imageOutput(outputId, width, height, click, dblclick, 
        hover, hoverDelay, hoverDelayType, brush, clickId, hoverId, 
        inline)
    res$attribs$class <- "shiny-plot-output"
    res
}
<bytecode: 0x00000296ece27b88>
<environment: namespace:shiny>
attr(,"outputArgs")
list()
attr(,"hasExecuted")
<Mutable>
  Public:
    clone: function (deep = FALSE) 
    get: function () 
    set: function (value) 
  Private:
    value: FALSE

**Comment by lecy** [comment]
That's precisely what you should get. Recall that shiny functions convert R objects to HTML/Javascript. 

This is why running shiny inside of chunks is not that helpful - you are better off running the whole document and testing the widgets.

**Comment by RickyDuran** [comment]
Perfect! Goal all my quirks figured out! 

I did also receive an error for "trying to use CRAN without an error, but added **,repos = "http://cran.us.r-project.org"** into the install code, and got it to go away. (Just a heads up if it comes up for anyone else. 

`install.packages( "shiny",repos = "http://cran.us.r-project.org" )
install.packages( "flexdashboard",repos = "http://cran.us.r-project.org" )`

**Comment by jmacost5** [comment]
I am getting errors too, what packages do I need for this lab? I get this message when I run the first chunklibrary( dplyr )
library( Lahman )
data( Teams )
ave.so <- Teams$SO / Teams$G

# min and max values needed to create your plot window 
ave.so.min <- min( ave.so, na.rm=T )
ave.so.max <- max( ave.so, na.rm=T )

# the league average for each season
league.ave <- tapply( X=ave.so, INDEX=as.factor(year), FUN="mean", na.rm=T )
league.year <- as.numeric( names( league.ave ) )
Error in is.factor(x) : object 'year' not found
and then I get this when I run my step 2 chunk:
selectInput( inputId= "team.widget",   # creates slot in input to hold values: input$your_inputId
             label= "Choose A Team",     # title of the input widget
             choices= "Cincinnati Reds", "Pittsburgh Pirates" , "Philadelphia Phillies" , "St. Louis Cardinals", "Chicago White Sox", "Detroit Tigers Chicago Cubs", "Boston Red Sox","New York Yankees" , "Cleveland Indians" ,   # options for the user
             selected=  "Cincinnati Reds" # set the default option
           )Error in selectInput(inputId = "team.widget", label = "Choose A Team",  : 
  unused arguments ("Detroit Tigers Chicago Cubs", "Boston Red Sox", "New York Yankees", "Cleveland Indians")

**Comment by lecy** [comment]
You need the **shiny** package. Note from the conversation above, to check progress you need to run the document, not a single chunk.

**Comment by sunaynagoel** [comment]
I tried to follow all the steps listed above. 
I did install Shiny Package, It did restart my R. 
When I try to run the file it gives me error that I need to install Shiny. 
When I try to run the chunk it gives me error that " could not find function SelectInput"
Not sure what I am doing wrong?

**Comment by lecy** [comment]
Can you close down R Studio and open it back up, then try running the file. 

If it doesn't run, then type `library( shiny )` in the console. What do you get?

**Comment by jmacost5** [comment]
I did install shinny

**Comment by sunaynagoel** [comment]
> Can you close down R Studio and open it back up, then try running the file.
> 
> If it doesn't run, then type `library( shiny )` in the console. What do you get?

@lecy I installed "shiny" in R console ans it shows following message
> install.packages( "shiny" )
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/shiny_1.3.2.tgz'
Content type 'application/x-gzip' length 4655011 bytes (4.4 MB)
==================================================
downloaded 4.4 MB


The downloaded binary packages are in
	/var/folders/nr/ws6grp394l97p2_1ck4brfsw0000gn/T//Rtmp7wdAKN/downloaded_packages
After that I closed my R studio and opened it again. when I try to run my file, it gives following error. 
Loading required package: shiny
Error in source(global_r, local = FALSE) : 
  /Users/sunaynaagarwal/Downloads/Whole Body Global Regional Store Contact List 10.2013.xlsx:1:3: unexpected input
1: PK
      ^
Calls: <Anonymous> -> do.call -> <Anonymous> -> <Anonymous> -> source
Execution halted

**Comment by lecy** [comment]
@jmacost5 can you run the shiny widgets demo file? 

https://cdn.rawgit.com/DS4PS/Data-Science-Class/53c986f1/TEMPLATES/ShinyWidgetsDemo.Rmd

**Comment by sunaynagoel** [comment]
Give the same error

Loading required package: shiny
Error in source(global_r, local = FALSE) : 
  /Users/sunaynaagarwal/Downloads/Whole Body Global Regional Store Contact List 10.2013.xlsx:1:3: unexpected input
1: PK
      ^
Calls: <Anonymous> -> do.call -> <Anonymous> -> <Anonymous> -> source
Execution halted

**Comment by lecy** [comment]
@sunaynagoel You can load shiny using library without errors, but you can't run an RMD shiny file? 

Or you are getting the error when loading shiny?

**Comment by sunaynagoel** [comment]
@lecy  Yes I can load shiny function with errors but can't run RMD shiny file. I tried widget demo file as well. 

Not sure what is going wrong.

**Comment by sunaynagoel** [comment]
Can this mean anything? (Notice the last line in the message)
When I call for details on installed.packages ("shiny"), it gives following message

Package LibPath Version Priority Depends Imports LinkingTo Suggests Enhances
     License License_is_FOSS License_restricts_use OS_type Archs MD5sum
     NeedsCompilation Built

What can I do on my part to do compilation? do I even need it?

**Comment by lecy** [comment]
I was going to suggest it might be a permissions problem accessing the file in the location it is currently saved. Can you try moving the file to the documents folder or desktop? 

What is your OS? Mac or PC?

**Comment by sunaynagoel** [comment]
I have a mac. I am trying to look for my permission etc. I already reinstalled R. It is giving the same error. Now I am trying to update R studio.

**Comment by sunaynagoel** [comment]
My shiny is still not working but I have another question. 
For dynamic widgets, is it possible to create a vector to store all the dynamic choices of team names rather than entering them ourself?

**Comment by sunaynagoel** [comment]
> I was going to suggest it might be a permissions problem accessing the file in the location it is currently saved. Can you try moving the file to the documents folder or desktop?
> 
> What is your OS? Mac or PC?

I think it is working now.

**Comment by lecy** [comment]
Regarding vectors of team names, there are some examples at the bottom of the lab. 

You can also do things like:

```r
t1 <- table( Teams$name )
t2 <- t1[ t1 > 100 ]  # teams that appear more than 100 times
names.vector <- names( t2 )
```

**Comment by jmacost5** [comment]
> https://cdn.rawgit.com/DS4PS/Data-Science-Class/53c986f1/TEMPLATES/ShinyWidgetsDemo.Rmd

I found my error. Working through the rest of the problems.

**Comment by castower** [comment]
Hello all,

I know on the original example from NYT when you hover over the data points in the background a label appears to identify the team and some other details. Should our finished version be able to do this? Mine currently does not. It just filters through showing different trendlines for each team and I think that's what the instructions asked for, but what to be sure that I'm not missing something.

Thanks!

**Comment by lecy** [comment]
Nope! At this point you are just using the widget to change the yellow trend line. 

If you want to learn how to create hover-over graphics, though, you can check out the plotly package in R. 

https://plot.ly/r/line-and-scatter/

**Comment by castower** [comment]
Thank you! One other thing I noticed is that for some reason it seems some of the data points are missing. For instance, in the example data points for the San Francisco Giants start in 1900, but mine only appear starting in 1960ish. Did I do something wrong with my input?

Here is code:

```{r}
#Interactive code:
Teams$ave.so <- Teams$SO / Teams$G  # to make subsetable, add back to data frame
team.name <- input$Team

# adding season stats for the team:
dat.one.team <- filter( Teams, name == team.name )
points( x=dat.one.team$yearID, y=dat.one.team$ave.so, 
        pch=20,  cex=1.2, col="darkorange", type="o" )
```

**Comment by lecy** [comment]
Try this:

```r
filter( Teams, name == "San Francisco Giants"  ) # or correct name as written in database
```
Do you get data points from 1900? 

I suspect it is because the Giants changed their name, so the NYT maybe did some additional data standardization?

**Comment by castower** [comment]
> ```r
> filter( Teams, name == "San Francisco Giants"  )
> ```

The furthest it goes back is 1958, so they must have combined their old name with the current one.

**Comment by castower** [comment]
Looking at the data set again, it appears that they used the franchID variable instead of the team name because that goes back to 1883.

**Comment by lecy** [comment]
That makes sense. Did they change names or cities in 1958?

**Comment by castower** [comment]
Yes, they changed from the New York Giants to the San Francisco Giants. When I filtered the data that way, all of the points appeared.

I did the input as follows to correspond with the franchise ID:

```{r}
selectInput( inputId= 'Team',
             label= 'Select Team',
            choices= c( list (`National League` = list("Arizona Diamondbacks" = "ARI", "Atlanta Braves" = "ATL", "Chicago Cubs" = "CHC", "Cincinnati Reds" = "CIN","Colorado Rockies" = "COL","Houston Astros" = "HOU", "Los Angeles Dodgers" = "LAD", "Miami Marlins" = "FLR","Milwaukee Brewers" = "MIL", "New York Mets" = "NYM", "Philadelphia Phillies" = "PHI", "Pittsburgh Pirates" = "PIT", "San Diego Padres" = "SDP", "San Francisco Giants" = "SFG","St. Louis Cardinals" = "STL", "Washington Nationals" = "WSN"),
           `American League` = list("Baltimore Orioles" = "BAL", "Boston Red Sox" = "BOS", "Chicago White Sox" = "CHW", "Cleveland Indians" = "CLE", "Detroit Tigers" = "DET", "Kansas City Royals" = "KCR", "Los Angeles Angels of Anaheim" = "ANA", "Minnesota Twins" = "MIN", "New York Yankees" = "NYY", "Oakland Athletics" = "OAK", "Seattle Mariners" = "SEA", "Tampa Bay Rays" = "TBD", "Texas Rangers" = "TEX", "Toronto Blue Jays" = "TOR"))),
             selected= "SFG" 
           )
```

and then filtered by franchID:

```{r}
team.name <- input$Team
dat.one.team <- filter( Teams, franchID == team.name)
```

The only thing I can't seem to figure out is how to make the graph display a custom label. Currently, with this setting:

```{r}
text ( x=1905, y=8.3, col="darkorange", labels= team.name, cex=1, font=2, adj=0 )
```
my chart displays the franchise ID (for example SFG) and I'm wondering if there's a way to use the team name for the label? 

I tried to use dat.one.team$name, but that loads all of the team names on the graph instead of just the name for the selected team. Do you know if there is any way to accomplish just displaying that one name instead of the variable name?

**Comment by lecy** [comment]
It's a little tricky. Try something like:

```r
# american league only - need to add national league teams 
d1 <- list("Arizona Diamondbacks" = "ARI", "Atlanta Braves" = "ATL", "Chicago Cubs" = "CHC", "Cincinnati Reds" = "CIN","Colorado Rockies" = "COL","Houston Astros" = "HOU", "Los Angeles Dodgers" = "LAD", "Miami Marlins" = "FLR","Milwaukee Brewers" = "MIL", "New York Mets" = "NYM", "Philadelphia Phillies" = "PHI", "Pittsburgh Pirates" = "PIT", "San Diego Padres" = "SDP", "San Francisco Giants" = "SFG","St. Louis Cardinals" = "STL", "Washington Nationals" = "WSN")

d2 <- unlist(d1)

franchise.name <- names(d2)
franchise.id <- as.character( d2 )
```

Then something like:

```r
text ( ... labels= franchise.name[ franchise.id == team.name ], ... )
```

**Comment by castower** [comment]
> It's a little tricky. Try something like:
> 
> ```r
> # american league only - need to add national league teams 
> d1 <- list("Arizona Diamondbacks" = "ARI", "Atlanta Braves" = "ATL", "Chicago Cubs" = "CHC", "Cincinnati Reds" = "CIN","Colorado Rockies" = "COL","Houston Astros" = "HOU", "Los Angeles Dodgers" = "LAD", "Miami Marlins" = "FLR","Milwaukee Brewers" = "MIL", "New York Mets" = "NYM", "Philadelphia Phillies" = "PHI", "Pittsburgh Pirates" = "PIT", "San Diego Padres" = "SDP", "San Francisco Giants" = "SFG","St. Louis Cardinals" = "STL", "Washington Nationals" = "WSN")
> 
> d2 <- unlist(d1)
> 
> franchise.name <- names(d2)
> franchise.id <- as.character( d2 )
> ```
> 
> Then something like:
> 
> ```r
> text ( ... labels= franchise.name[ franchise.id == team.name ], ... )
> ```

That worked! Thank you so much!

**Comment by jmacost5** [comment]
I am not understanding how to program the code to go to the specific widget. The Chicago Reds is the only one showing up and I don't understand how make the other teams populate other than doing the same function copy and paste the same thing for each team and then they would all populate on the main screen. Also I do not understand how to get the widget to link to the line plotted, here is my codeTeams$ave.so <- Teams$SO / Teams$G  # to make subsetable, add back to data frame
one.team <- filter( Teams, name == "Cincinnati Reds" )
points( x=one.team$yearID, y=one.team$ave.so, type="b", pch=19, col="darkorange4" )
team.name <- "Cincinnati Reds" # only place it appears
dat.one.team <- filter( Teams, name == team.name )
points( x=dat.one.team$yearID, y=dat.one.team$ave.so, 
        pch=20,  cex=1.2, col="goldenrod1", type="b" )
segments( x0=1900, y0=8.3, x1=1904, y1=8.32, col="goldenrod1", lwd = 1.5 )
points(  league.year, league.ave, col="goldenrod1", pch=20, cex=1.2 )
text ( x=1915, y=8.3, col="goldenrod1", labels=team.name, cex=0.8 )

Do I need to add a variable? Do I need to change the "Cincinnati Reds" to something else?

**Comment by lecy** [comment]
@jmacost5 Read the section **Adding a Team Trend to the Graph** on the lab instructions. 

https://ds4ps.org/cpp-526-fall-2019/LABS/lab-04-instructions.html

**Comment by jmacost5** [comment]
So for the team.name function I need to put team.name <- input$my_widget_id  # input widget value in order for it to work? Do I need to put it under the choices c(...) and list the teams?

**Comment by jmacost5** [comment]
I am sorry I read it through a few times and I am just not understanding because I am confused if I put in the code, neither work

**Comment by lecy** [comment]
`team.name` is just a placeholder variable for whichever team the user has selected. 

The widget values are stored on the `input` object at the name slot that you designate (**inputID=** on the `selectInput()` function). 

You are assigning the user selection to the variable. Then using the variable in place of a specific team name in your code.

**Comment by lecy** [comment]
What did you name your widget? ` input$my_widget_id`

**Comment by jmacost5** [comment]
no I named it "team.widget", so when I put that in it shows the"team.widget" and when I click on the different options it does not put the trend lines in for the teams. selectInput( inputId= "team.widget",   # creates slot in input to hold values: input$your_inputId
             label= "Select A Team",     # title of the input widget
             choices= c("Cincinnati Reds", "Pittsburgh Pirates", "St. Louis Cardinals"  , "Chicago White Sox", "Detroit Tigers", "Chicago Cubs", "Boston Red Sox", "New York Yankees","Cleveland Indians", "Arizona Dimondbacks"), # options for the user
             selected= "Cincinnati Reds"   # set the default option
           )
team.name <- "team.widget" # input widget value
Teams$ave.so <- Teams$SO / Teams$G  # to make subsetable, add back to data frame
one.team <- filter( Teams, name == team.name )
points( x=one.team$yearID, y=one.team$ave.so, type="b", pch=19, col="darkorange4" )
dat.one.team <- filter( Teams, name == team.name )
points( x=dat.one.team$yearID, y=dat.one.team$ave.so, 
        pch=20,  cex=1.2, col="goldenrod1", type="b" )
segments( x0=1900, y0=8.3, x1=1904, y1=8.32, col="goldenrod1", lwd = 1.5 )
points(  league.year, league.ave, col="goldenrod1", pch=20, cex=1.2 )
text ( x=1915, y=8.3, col="goldenrod1", labels=team.name, cex=0.8 )

**Comment by lecy** [comment]
Try:

```r
team.name <- input$team.widget
```

Also, please format your questions with markdown. I'm having a hard time separating code and text.

**Comment by lecy** [comment]
Review the notes on Shiny - the shiny functions work a little different than others. 

https://github.com/DS4PS/cpp-526-fall-2019/raw/master/lectures/shiny-widgets.pdf

And look at the code for the input widgets in the demo file. That would probably help clarify.

 https://cdn.rawgit.com/DS4PS/Data-Science-Class/53c986f1/TEMPLATES/ShinyWidgetsDemo.Rmd

**Comment by katiegentry07** [comment]
When I try to run the document, it gives me the following error:

Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Scanner error: while scanning for the next token at line 3, column 7 found character that cannot start any token at line 3, column 7
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
Execution halted

It gives me the same error when I've tried to run the demo. Any advice?

**Comment by lecy** [comment]
I searched for "Error in yaml::yaml.load(..., eval.expr = TRUE) :" and here is what comes up:

https://community.rstudio.com/t/error-in-yaml-yaml-load-eval-expr-true-unused-argument-eval-expr-true-calls-anonymous-parse-yaml-front-matter-yaml-load-anonymous-execution-halted/27080/2

> You need to update yaml, rmarkdown, and knitr package :package: . One of them is too old to work with the other.

Under **tools** you can search for package updates.

**Comment by katiegentry07** [comment]
Thank you! I reinstalled the latest package of R which seemed to help. 

I'm also having an error in this set of pre-loaded code into the RMD document stating that the object 'year' cannot be found. I'm assuming it is in the second to last line, but cannot figure out where I'm going wrong. 

```{r global, include=FALSE}
library( dplyr )
library( Lahman )
data( Teams )
ave.so <- Teams$SO / Teams$G

# min and max values needed to create your plot window 
ave.so.min <- min( ave.so, na.rm=T )
ave.so.max <- max( ave.so, na.rm=T )

# the league average for each season
league.ave <- tapply (x=ave.so, INDEX = as.factor (year), FUN="mean", na.rm=T)
league.year <- as.numeric( names( league.ave ) )
```

**Comment by lecy** [comment]
If you look back at Lab-03 you can see where the year variable is created.

```r
ave.so <- Teams$SO / Teams$G  # average strike-outs per game each season 
year <- Teams$yearID
```

**Comment by etbartell** [comment]
I know this is last minute, but I'm now realizing that R Studio is not letting me knit the rmd doc. It only has the option to "Run Document", which generates the graph I'm looking for but doesn't appear to create an html document. Is there a setting I'm not aware of that disables the knit feature? Here's the link to my graph:

http://127.0.0.1:3342/Lab-04-Bartell.Rmd

**Comment by castower** [comment]
The shiny documents don't create .html files so Prof. Lecy said we can just
turn in our files in RMD form for this assignment.

**Comment by etbartell** [comment]
Didn't catch that. Thank you!

**Comment by lecy** [comment]
Courtney is correct! 

Javascript is the language that makes visualizations dynamic. Once you add javascript to a file you need to host it on a server, you can no longer share as a single file like static HTML pages. 

So yes, you are submitting the RMD file only this week.

**Comment by Jigarci3** [comment]
I have not been able to figure out how to add the team trend line to my graphic. I have read through the lab instructions and unit readings- I have tried several codes and have not had any success.

The latest code I am trying is

```{r}
team.name <- input$team.widget
team.name <- "Chicago Cubs"
dat.one.team <- filter( Teams, name == "Chicago Cubs" )
points( x=dat.one.team$yearID, y=dat.one.team$ave.so, 
        pch=20,  cex=1.2, col="goldenrod1", type="b" )
```

The error I receive is 
"Error: Operation not allowed without an active reactive context. (You tried to do something that can only be done from the inside a reactive expression or observer.)"

What am I missing?
Any guidance would be appreciated! I was successful in creating the user input widget but need help linking the drop down options to the team's trend lines. Please help.

**Comment by lecy** [comment]
You must have moved the code from where it was in the template?  Can you email me your RMD? 

The main problem you have here is you are capturing your input as **team.name** then in the next line you are over-writing your user input with "Chicago Cubs". The easy fix is to get rid of the Cubs, then the rest looks ok. 

What did you use for your widget inputId? 

```r
team.name <- input$team.widget
# team.name <- "Chicago Cubs"
dat.one.team <- filter( Teams, name == "Chicago Cubs" )
points( x=dat.one.team$yearID, y=dat.one.team$ave.so, 
        pch=20,  cex=1.2, col="goldenrod1", type="b" )
```

**Comment by Jigarci3** [comment]
@lecy I think I had been staring at the assignment for too long. I finally got my code working. Thank you!
